### ISSUE TITLE
Crash on react elements in props

### ISSUE THREAD

**Issue by AndrewRayCode** [alexlande/react-to-jsx#13]
From https://github.com/alexlande/react-style-guide/issues/3

Crashes if your props are react elements:

```
Uncaught TypeError: Converting circular structure to JSON
```

**Comment by AndrewRayCode** [comment]
ping

**Comment by alexlande** [comment]
Sorry :) Meant to take care of this over the weekend. I'll check out your PRs and try to get a release out tonight.

**Comment by alexlande** [comment]
Resolved with #16
