### ISSUE TITLE
<input/> element would display undefined props

### ISSUE THREAD

**Issue by jessy1092** [alexlande/react-to-jsx#5]
When I use react-to-jsx to translate the default input element, it would display the undefined or null props.
ex.

``` html
<input className="123" \>
```

After use react-to-jsx, jsx string would become

``` html
<input
    className="123"
    style={null}
    styles={undefined}/>
```

Could it ignore the null or undefined props?

**Comment by alexlande** [comment]
Oof, sorry I missed this PR, I had my notifications turned off for this repo, which is fun...

Will look into this. Definitely agree that `undefined` shouldn't be displayed. I'm on the fence about `null`. It seems like there might be a valid use case for displaying that (if you're overriding default props, for example). Might make it optional though. I've also got an issue to omit props, which would help as well: #4.

**Comment by jessy1092** [comment]
:+1:
